# Generated by Django 5.1.2 on 2024-11-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Creation'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Creation'),
        ),
        migrations.AlterField(
            model_name='date',
            name='parent_subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date', to='tracker.subtask'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_task', to='tracker.task'),
        ),
    ]
