# Generated by Django 5.1.2 on 2024-11-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_subtask_date_created_task_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='subtask_name',
            new_name='subtask',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='date',
            name='parent_subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tracker.subtask'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tracker.task'),
        ),
    ]
