# Generated by Django 5.1.2 on 2024-11-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_subtask_name_subtask_subtask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
