# Generated by Django 5.1.2 on 2025-05-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_subtask_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='subtask',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='parent_task',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='date',
            name='parent_subtask',
        ),
        migrations.AddField(
            model_name='date',
            name='subtask',
            field=models.ManyToManyField(related_name='dates', to='tracker.subtask'),
        ),
    ]
