# Generated by Django 5.1.2 on 2025-06-10 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rename_subtask_subtask_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='subtask',
        ),
        migrations.AddField(
            model_name='date',
            name='subtask',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tracker.subtask'),
            preserve_default=False,
        ),
    ]
